networks:
  dev-langflow:

services:
  langflow:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    image: dev-langflow
    tty: true
    container_name: dev-langflow
    restart: always
    ports:
      - "7860:7860"
      - "3000:3000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - LANGFLOW_DATABASE_URL=postgresql://postgres:1@postgres:5432/cloudcix
      - LANGFLOW_SUPERUSER=postgres
      - LANGFLOW_SUPERUSER_PASSWORD=1
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - postgres
    networks:
      -  dev-langflow

  # postgres:
  #   container_name: postgres
  #   image: pgvector/pgvector:pg16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1
  #     POSTGRES_DB: cloudcix
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     -  dev-langflow
